version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: notion_postgres
    restart: always
    environment:
      POSTGRES_USER: notion-test
      POSTGRES_PASSWORD: notiontest999
      POSTGRES_DB: notion-test
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: notion_backend
    restart: always
    env_file:
      - ./packages/backend/.env
    environment:
      - DB_PORT=5432
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command: npm run start:dev

volumes:
  postgres_data:
